### ISSUE TITLE
profiles.

### ISSUE THREAD

**Issue by necrose99** [Jannik2099/pinebookpro-overlay#8]
https://github.com/sakaki-/genpi64-overlay/tree/master/profiles

for rockpro64 /pinebook pro ...  other than tablet mode , r64pro also nice to have as /disfiles /packages and gp NAS /distcc along with RPI4 r64 for compute nodes. 

while sakis bins will run , on either , adding profile links. a plus. 

ie packages mask 

https://github.com/ayufan-rock64/chromiumos-build needs porting ..

https://github.com/psychedup/gentoo-pine64 kernel ebuild skells added but needs work 

if only you could rig firmware atf to load r64/pro/pinebook-pro...
https://github.com/tianocore/edk2-platforms  dose have an R-64-pro and r64-pro seems to load the pb-pro. also..  has u-boot/atf bits ie elf compiled in fails if you dont. 
https://github.com/andreiw/rk3399-edk2/  ebuild for the UEFI loader2 firmware awould be a plus..
can be built but not as easily.  and ebuild ... dear loard. 

grub2 efi  
/boot/efi 
./efi/overlay 
/boot/overlay >>> /boot/efi/overlay SYM for compatibility ... 

loader/s 
/boot/efi
/boot 
/  

https://www.dropbox.com/sh/gfsfqv3p4lvnzi6/AAAE-Mb_8ko1oX3xSROVkP8ia?dl=0  
grub or sysd-boot should work with the above , i need to cp file from atf into /workspace$ 

ayufan also has repos supporting rock64 /p-book-pro  etc variants. 

https://github.com/ayufan-rock64/pinebook-pro-keyboard-updater 

https://github.com/ayufan-rock64/linux-package now updated to pinebookpro

**Comment by necrose99** [comment]
gentoo patches can be added to kernel/s ...

**Comment by Jannik2099** [comment]
These profiles look kinda unmaintained to me. I'd like to stay as close to upstream as possible with profiles, only adding overrides for stuff that is almost 100% necessary, like gles2.

About the bootloader situation: neither grub nor uboot have an eDP driver for the rk3399, so anything with boot menus won't be of much use.
I added uboot support to genkernel, so there's no benefit in using grub right now. We can reconsider this in the distant future when anyone implements an eDP driver

**Comment by necrose99** [comment]
Far as rpi4  Sakaki keeps them up, however,  useful as templates.  And or packages on mask ie rpi4/rpi3 items , and items req.  Could be added to add packages , mask packages 

https://github.com/necrose99/gentoo-binhost
/loaders
/esp. /boot/efi 
/boot 
/ 
Grub with uboot dev-embeded/uboot tools. Etc 
Makes easy to display boot menu briefly,  debian  uses. Grub-efi.   
Point is making kernel upgrades swapping easy.
For r64pro,  needs overlay/driver for edp./screen.. 

Fresh versions,  of uboot,  will work with efi. 
Added repo a few pinebookpro pkgs. 
Chroot on rockpro64,  

Ayufan makes much of debian or Chromeos ubuntu etc.

**Comment by necrose99** [comment]
grub in gentoo also needs UBOOT patched for arm64 ,  and and for bootloader ,
meanwihile (debian etc already has) dracut/plymout/etc already built. 

uboot rock64/rock64pro/pinebookpro  ?> univ-rk   if uboot would let you compile board.a b ,c, d uboot-stub link > uboot out..

however ways of oddly con-cati'nation of them however how to join bins so more than 1 system boots... ughhh

RP4, rock64-pro , with 8 gig RPI4 holding out for pb-pro etc to offer in 8 gigs etc ram ... 

http://gpo.zugaina.org/app-eselect/eselect-uimage  might be of use in modding to new-kernl.img curent.img /> swap etc..

**Comment by necrose99** [comment]
https://github.com/andreiw/rk3399-edk2

https://stikonas.eu/wordpress/2019/09/15/blobless-boot-with-rockpro64/
